const kGoogleApiKey = 'AIzaSyBiXvU9qsq3uGUw9muMIcslDOaVSRIIVcI';

const kStripeKey = 'pk_test_51ILLBgIqNPuCGoK3RDHpDvK4K4hGrXkTkPGk0VvoOHLKCbFbftMlSRDPGFyzUFRQNpV6k00nuCwVs89leGmFSG6g00vYUiOJWZ';
const kStripeSecret = 'sk_test_51ILLBgIqNPuCGoK3klH1ETAApOqU1eIcjDVl4Kq8wgaUJuHECBwoSOzBJEOA7UkNcn6MynPnVmLevODUogtGzsng00bqeJdrT1';